name: Build docker images

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read version
        run: |
          echo "NODE_VERSION=$(cat packages/alpine-node-nginx/version)" >> $GITHUB_ENV

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          path: packages/alpine-node-nginx/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: alfabankui/arui-scripts
          build_args: NODE_VERSION=${{ env.NODE_VERSION }}
          tag_with_ref: true
          tags: ${{ env.NODE_VERSION }}
          cache_froms: alfabankui/arui-scripts:latest
