name: Create new library package

on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'NPM channel to use'
        required: true
        default: 'next'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: create new version
        run: |
          cd packages/arui-scripts
          yarn --immutable && yarn build && yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PERMISSION_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          WORK_SPACE: ${{ github.workspace }}
          NPM_CHANNEL: ${{ github.event.inputs.channel }}
          CI: true
